interface agg-ticker {

    record aggregated-tickers {
        instrument-name: string,
        strike: f64,
        kind: string,
        delta: f64,
        bids: list<tuple<f64, f64, f64, f64, string>>,
        asks: list<tuple<f64, f64, f64, f64, string>>,
        timestamp: u64,
    }

    aggregate: func(instrument-name: string) -> result<aggregated-tickers, string>;
    aggregate-and-publish: func(instrument-name: string);
}