package jabratech:component-agg-ticker;

world component-agg-ticker {
    import wasi:logging/logging;
    import wasi:random/random@0.2.0;
    import wasmcloud:messaging/consumer@0.2.0;

    export agg-ticker;
}